name: project1
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.2
  firebase_core: ^2.9.0
  built_collection: ^5.1.1
  firebase_database: ^10.1.0
  flutterfire_ui: ^0.4.3+20
  firebase_auth: ^4.4.0
  pie_chart: ^5.3.2
  flutter_local_notifications: ^14.0.0+1
  flutter_native_timezone: ^2.0.0
  currency_picker: ^2.0.16
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.0.3


flutter:
  uses-material-design: true
  assets:
    - assets/finance.png
    - assets/left.png
    - assets/right.png

flutter_icons:
  android: true
  image_path: "assets/finance.png"

